<a href="https://colab.research.google.com/github/mnilanjana/Python4DS/blob/master/assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

assignment


In [180]:
import numpy as np

In [181]:
a=[1,2,3,4,5]
a=np.array([1,2,3,4,5])
print(a)

TypeError: ignored

In [179]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]

In [178]:
matrix2 = np.matrix([list1,list2,list3])
matrix2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [177]:
matrix2.shape

(3, 3)

In [176]:
matrix2=np.array([list1,list2,list3])
print(matrix2)

TypeError: ignored

In [173]:
start, end = 1, 17
  
# iterating each number in list 
for num in range(start, end + 1): 
      
    # checking condition 
    if num % 2 != 0: 
        print(num, end = " ") 



1 3 5 7 9 11 13 15 17 

In [172]:
list=([1,3,5,7,9,11,13,15,17])
arr2 = np.arange(list).reshape(3,3)

TypeError: ignored

In [171]:
n = 3
p = 3
np.array([[(i+j)%2 for i in range(n)] for j in range(p)])

TypeError: ignored

In [170]:
list4=[1,3,5]
list5=[7,9,11]
list6=[13,15,17]

In [169]:
matrix3 = np.matrix([list4,list5,list6])
matrix3

matrix([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]])

In [168]:
matrix3.shape

(3, 3)

In [167]:
arr2 = np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
np.reshape(arr,(5,1))

TypeError: ignored

In [ ]:
arr.shape

In [165]:
arr1 = np.array=([1,2,5,6,3,8,9,4,2,6])
arr1
print(np.array)

[1, 2, 5, 6, 3, 8, 9, 4, 2, 6]


In [161]:
arr1[3]

6

In [162]:
arr1[4]

3

In [163]:
arr1[9]

6

In [164]:
arr1[-1]

6

In [160]:
arr1 = np.array=([1,2,5,6,3,8,9,4,2,6])
arr1
arr1[-3:]=100
arr1

TypeError: ignored

In [157]:
arr3 = np.arange(0,25).reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

IndexError: ignored

In [ ]:
arr3[3]


In [155]:
arr3[2]

array([21, 23, 25, 27, 29])

In [154]:
#5*5 natrix
arr3=np.arange(1,51,2).reshape(5,5)
print(repr(arr3))

print(arr3[1:4,1:4])




array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])
[[13 15 17]
 [23 25 27]
 [33 35 37]]
